---
default_install_hook_types:
  - pre-commit
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args:
          - --unsafe
      - id: check-added-large-files
      - id: check-merge-conflict
  - repo: local
    hooks:
      - id: lint-check
        name: Quality and Formatting (Hatch)
        entry: hatch run lint:check
        language: python
        additional_dependencies:
          - hatch
          - uv
        types_or:
          - python
          - markdown
          - yaml
        pass_filenames: false
      - id: type-check
        name: Type Check (Hatch)
        entry: hatch run types:check
        language: python
        additional_dependencies:
          - hatch
          - uv
        types:
          - python
        pass_filenames: false
